# Part 1 - Data Preprocessing

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
X #CreditScore, ...

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

#### 1. Encoding categorical data

In [3]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [4]:
#encode country
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
X 

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [6]:
#encode gender
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
X = pd.DataFrame(X)
X

0  1  2   3   4        5  6  7  8        9
0     619  0  0  42   2        0  1  1  1   101349
1     608  2  0  41   1  83807.9  1  0  1   112543
2     502  0  0  42   8   159661  3  1  0   113932
3     699  0  0  39   1        0  2  0  0  93826.6
4     850  2  0  43   2   125511  1  1  1  79084.1
5     645  2  1  44   8   113756  2  1  0   149757
6     822  0  1  50   7        0  2  1  1  10062.8
7     376  1  0  29   4   115047  4  1  0   119347
8     501  0  1  44   4   142051  2  0  1  74940.5
9     684  0  1  27   2   134604  1  1  1  71725.7
10    528  0  1  31   6   102017  2  0  0  80181.1
11    497  2  1  24   3        0  2  1  0    76390
12    476  0  0  34  10        0  2  1  0    26261
13    549  0  0  25   5        0  2  0  0   190858
14    635  2  0  35   7        0  2  1  1  65951.6
15    616  1  1  45   3   143129  2  0  1  64327.3
16    653  1  1  58   1   132603  1  1  0  5097.67
17    549  2  0  24   9        0  2  1  1  14406.4
18    587  2  1  45   6        0  1  0  0   158685
19    726  0  0  24   6        0  2  1  1    54724
20    732  0  1  41   8        0  2  1  1   170886
21    636  2  0  32   8        0  2  1  0   138555
22    510  2  0  38   4        0  1  1  0   118914
23    669  0  1  46   3        0  2  0  1  8487.75
24    846  0  0  38   5        0  1  1  1   187616
25    577  0  1  25   3        0  2  0  1   124508
26    756  1  1  36   2   136816  1  1  1   170042
27    571  0  1  44   9        0  2  0  0  38433.3
28    574  1  0  43   3   141349  1  1  1   100187
29    411  0  1  29   0  59697.2  2  1  1  53483.2
...   ... .. ..  ..  ..      ... .. .. ..      ...
9970  518  0  1  42   7   151027  2  1  0   119377
9971  833  0  0  34   3   144752  1  0  0   166473
9972  758  0  1  26   4   155740  1  1  0   171552
9973  611  0  1  27   7        0  2  1  1   157474
9974  583  0  1  33   7   122532  1  1  0  13549.2
9975  610  1  1  50   1   113957  2  1  0   196527
9976  637  0  0  33   7   103378  1  1  0  84419.8
9977  683  0  0  32   9        0  2  1  1  24991.9
9978  774  0  1  40   9  93017.5  2  1  0   191609
9979  677  0  0  58   1  90022.9  1  0  1  2988.28
9980  741  2  1  35   6  74371.5  1  0  0  99595.7
9981  498  1  1  42   3   152040  1  1  1  53445.2
9982  655  1  0  46   7   137145  1  1  0   115146
9983  613  0  1  40   4        0  1  0  0   151325
9984  602  1  1  35   7  90602.4  2  1  1  51695.4
9985  659  0  1  36   6   123841  2  1  0    96833
9986  673  1  1  47   1   183580  2  0  1  34047.5
9987  606  2  1  30   8   180308  2  1  1  1914.41
9988  775  0  1  30   4        0  2  1  0  49337.8
9989  841  2  1  28   4        0  2  1  1   179437
9990  714  1  1  33   3  35016.6  1  1  0  53667.1
9991  597  0  0  53   4  88381.2  1  1  0  69384.7
9992  726  2  1  36   2        0  1  1  0   195192
9993  644  0  1  28   7   155060  1  1  0  29179.5
9994  800  0  0  29   2        0  2  0  0   167774
9995  771  0  1  39   5        0  2  1  0  96270.6
9996  516  0  1  35  10  57369.6  1  1  1   101700
9997  709  0  0  36   7        0  1  0  1  42085.6
9998  772  1  1  42   3  75075.3  2  1  0  92888.5
9999  792  0  0  28   4   130143  1  1  0  38190.8

[10000 rows x 10 columns]

##### Convert country category into one-hot encoding
Country becomes three columns -> binary mode

In [7]:
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray() #Column: 0-2
X = X[:, 1:] #Exclude the col to avoid dummy variable trap (one variable can be predicted from others/variable redundant)

In [8]:
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

#### 2. Splitting the dataset into the Training set and Test set

In [0]:
X=pd.DataFrame(X)

In [0]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

/anaconda/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


#### 3. Feature Scaling

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train = pd.DataFrame(X_train)

# Part 2 - Make the ANN

In [0]:
import keras
from keras.models import Sequential #initialize NN
from keras.layers import Dense #create layer

/anaconda/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


### 1. Initialising the ANN

In [0]:
classifier = Sequential()

### 2. Apply the activation function

#### adding the input layer and first hidden layer

1. output_dim: the number of nodes of the layer we are adding in this function
= the average of the number of nodes in input layer (12, 12 attributes) and the number of nodes in output layer (1)
= 6

2. init: initialize the weights to a small number close to zero
    uniform: initialize the function according to a uniform distribution

3. activation function

4. input_dim: independent variables (only need to be created when creating the first hidden layer)

In [0]:
classifier.add(Dense(output_dim=6, init='uniform', activation='relu', input_dim=11))

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


#### adding the second hidden layer

In [0]:
classifier.add(Dense(output_dim=6, init='uniform', activation='relu'))

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


#### adding the output layer

In [0]:
classifier.add(Dense(output_dim=1, init='uniform', activation='sigmoid'))

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


#### Compiling the ANN

In [0]:
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

#### Fitting the ANN to the Training set
1. batch_size:  Number of samples per gradient update
2. epoch: An epoch is an iteration over the entire x and y data provided.

In [0]:
classifier.fit(X_train, y_train, batch_size=10, nb_epoch=100)

/anaconda/lib/python3.6/site-packages/keras/models.py:942: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/100
8000/8000 [==============================] - 2s 305us/step - loss: 0.4871 - acc: 0.7949
Epoch 2/100
8000/8000 [==============================] - 2s 221us/step - loss: 0.4303 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 188us/step - loss: 0.4269 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 2s 213us/step - loss: 0.4229 - acc: 0.8010
Epoch 5/100
8000/8000 [==============================] - 2s 215us/step - loss: 0.4193 - acc: 0.8200
Epoch 6/100
8000/8000 [==============================] - 2s 218us/step - loss: 0.4169 - acc: 0.8262
Epoch 7/100
8000/8000 [==============================] - 2s 234us/step - loss: 0.4148 - acc: 0.8287
Epoch 8/100
8000/8000 [==============================] - 2s 206us/step - loss: 0.4135 - acc: 0.8319
Epoch 9/100
8000/8000 [==============================] - 2s 224us/step - loss: 0.4122 - acc: 0.8337
Epoch 10/100
8000/8000 [==============================] - 2s 220us/step - loss: 0.4112 - acc: 0.8332

# Part 3 - Making the predictions and evaluating the model

In [0]:
y_pred = classifier.predict(X_test)
y_pred

array([[0.16652966],
       [0.35550457],
       [0.17308044],
       ...,
       [0.15969078],
       [0.1615027 ],
       [0.08592274]], dtype=float32)

#### Convert the probability to true or false

In [0]:
y_pred = (y_pred > 0.5) #if > 0.5, return true
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

#### Making the confusion matrix

In [0]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1541,   54],
       [ 268,  137]])

In [0]:
accuracy = (1547 + 144)/2000
accuracy

0.8455

### Use our ANN model to predict if the customer with the following informations will leave the bank: 

In [0]:
new_X = np.array([[600, 'France', 'Male', 40, 3, 60000, 2, 1, 1, 50000]])
new_X

array([['600', 'France', 'Male', '40', '3', '60000', '2', '1', '1',
        '50000']], dtype='<U21')

In [0]:
#Encode Country
new_X[:, 1] = labelencoder_X_1.transform(new_X[:, 1])

In [0]:
new_X

array([['600', '0', 'Male', '40', '3', '60000', '2', '1', '1', '50000']],
      dtype='<U21')

In [0]:
#Encode Gender
new_X[:, 2] = labelencoder_X_2.transform(new_X[:, 2])
new_X

array([['600', '0', '1', '40', '3', '60000', '2', '1', '1', '50000']],
      dtype='<U21')

In [0]:
#one-hot encoding
new_X = onehotencoder.transform(new_X).toarray()
new_X = new_X[:, 1:]

In [0]:
new_X = sc.transform(new_X)
new_X

array([[-0.5698444 , -0.57369368, -0.52111599,  0.91601335,  0.10961719,
        -0.68538967, -0.2569057 ,  0.8095029 ,  0.64259497,  0.9687384 ,
        -0.87203322]])

In [0]:
new_pred = classifier.predict(new_X)
new_pred = (new_pred > 0.5)
new_pred

array([[False]])

## Part 4 - Evaluating, Improving and Tuning the ANN
### Evaluating the ANN

In [0]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [0]:
def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(output_dim=6, init='uniform', activation='relu', input_dim=11))
    classifier.add(Dense(output_dim=6, init='uniform', activation='relu'))
    classifier.add(Dense(output_dim=1, init='uniform', activation='sigmoid'))
    classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return classifier

In [0]:
classifier = KerasClassifier(build_fn=build_classifier, batch_size=10, epochs=100)
# build_fn : a keras model

In [0]:
accuracies = cross_val_score(estimator=classifier, X=X_train, y=y_train, cv=10, n_jobs=1) 
#average accuracy from 10-fold cv
#n_jobs: -1 to use all the CPUs to train the model

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  after removing the cwd from sys.path.
/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """


Epoch 1/100
7200/7200 [==============================] - 2s 274us/step - loss: 0.4941 - acc: 0.7960
Epoch 2/100
7200/7200 [==============================] - 1s 201us/step - loss: 0.4291 - acc: 0.7971
Epoch 3/100
7200/7200 [==============================] - 1s 188us/step - loss: 0.4238 - acc: 0.7971
Epoch 4/100
7200/7200 [==============================] - 1s 190us/step - loss: 0.4199 - acc: 0.8101
Epoch 5/100
7200/7200 [==============================] - 2s 213us/step - loss: 0.4177 - acc: 0.8237
Epoch 6/100
7200/7200 [==============================] - 2s 234us/step - loss: 0.4157 - acc: 0.8242
Epoch 7/100
7200/7200 [==============================] - 2s 216us/step - loss: 0.4144 - acc: 0.8274
Epoch 8/100
7200/7200 [==============================] - 1s 206us/step - loss: 0.4129 - acc: 0.8310
Epoch 9/100
7200/7200 [==============================] - 1s 189us/step - loss: 0.4120 - acc: 0.8306
Epoch 10/100
7200/7200 [==============================] - 1s 200us/step - loss: 0.4111 - acc: 0.8318

7200/7200 [==============================] - 2s 209us/step - loss: 0.3383 - acc: 0.8646
Epoch 63/100
7200/7200 [==============================] - 1s 208us/step - loss: 0.3379 - acc: 0.8621
Epoch 64/100
7200/7200 [==============================] - 1s 189us/step - loss: 0.3381 - acc: 0.8624
Epoch 65/100
7200/7200 [==============================] - 1s 188us/step - loss: 0.3378 - acc: 0.8603
Epoch 66/100
7200/7200 [==============================] - 1s 191us/step - loss: 0.3387 - acc: 0.8603
Epoch 67/100
7200/7200 [==============================] - 1s 189us/step - loss: 0.3380 - acc: 0.8592
Epoch 68/100
7200/7200 [==============================] - 1s 188us/step - loss: 0.3377 - acc: 0.8615
Epoch 69/100
7200/7200 [==============================] - 2s 212us/step - loss: 0.3368 - acc: 0.8611
Epoch 70/100
7200/7200 [==============================] - 1s 206us/step - loss: 0.3380 - acc: 0.8600
Epoch 71/100
7200/7200 [==============================] - 1s 198us/step - loss: 0.3369 - acc: 0.8606
Epo

7200/7200 [==============================] - 2s 245us/step - loss: 0.3931 - acc: 0.8378
Epoch 23/100
7200/7200 [==============================] - 1s 192us/step - loss: 0.3931 - acc: 0.8381
Epoch 24/100
7200/7200 [==============================] - 1s 196us/step - loss: 0.3924 - acc: 0.8389
Epoch 25/100
7200/7200 [==============================] - 1s 191us/step - loss: 0.3926 - acc: 0.8379
Epoch 26/100
7200/7200 [==============================] - 1s 192us/step - loss: 0.3915 - acc: 0.8369
Epoch 27/100
7200/7200 [==============================] - 1s 205us/step - loss: 0.3921 - acc: 0.8372
Epoch 28/100
7200/7200 [==============================] - 1s 206us/step - loss: 0.3919 - acc: 0.8372
Epoch 29/100
7200/7200 [==============================] - 1s 200us/step - loss: 0.3915 - acc: 0.8379
Epoch 30/100
7200/7200 [==============================] - 1s 192us/step - loss: 0.3910 - acc: 0.8394
Epoch 31/100
7200/7200 [==============================] - 1s 191us/step - loss: 0.3914 - acc: 0.8382
Epo

7200/7200 [==============================] - 1s 198us/step - loss: 0.5090 - acc: 0.7937
Epoch 84/100
7200/7200 [==============================] - 1s 198us/step - loss: 0.5090 - acc: 0.7937
Epoch 85/100
7200/7200 [==============================] - 1s 197us/step - loss: 0.5090 - acc: 0.7937
Epoch 86/100
7200/7200 [==============================] - 2s 216us/step - loss: 0.5090 - acc: 0.7937
Epoch 87/100
7200/7200 [==============================] - 1s 206us/step - loss: 0.5090 - acc: 0.7937
Epoch 88/100
7200/7200 [==============================] - 1s 208us/step - loss: 0.5090 - acc: 0.7937
Epoch 89/100
7200/7200 [==============================] - 2s 227us/step - loss: 0.5090 - acc: 0.7937
Epoch 90/100
7200/7200 [==============================] - 1s 198us/step - loss: 0.5090 - acc: 0.7937
Epoch 91/100
7200/7200 [==============================] - 1s 196us/step - loss: 0.5090 - acc: 0.7937
Epoch 92/100
7200/7200 [==============================] - 1s 197us/step - loss: 0.5090 - acc: 0.7937
Epo

7200/7200 [==============================] - 2s 233us/step - loss: 0.4025 - acc: 0.8340
Epoch 44/100
7200/7200 [==============================] - 1s 201us/step - loss: 0.4022 - acc: 0.8356
Epoch 45/100
7200/7200 [==============================] - 1s 198us/step - loss: 0.4022 - acc: 0.8354
Epoch 46/100
7200/7200 [==============================] - 2s 216us/step - loss: 0.4024 - acc: 0.8351
Epoch 47/100
7200/7200 [==============================] - 2s 218us/step - loss: 0.4022 - acc: 0.8367
Epoch 48/100
7200/7200 [==============================] - 1s 197us/step - loss: 0.4019 - acc: 0.8358
Epoch 49/100
7200/7200 [==============================] - 2s 235us/step - loss: 0.4021 - acc: 0.8349
Epoch 50/100
7200/7200 [==============================] - 2s 216us/step - loss: 0.4022 - acc: 0.8347
Epoch 51/100
7200/7200 [==============================] - 1s 198us/step - loss: 0.4023 - acc: 0.8342
Epoch 52/100
7200/7200 [==============================] - 1s 202us/step - loss: 0.4017 - acc: 0.8357
Epo

7200/7200 [==============================] - 2s 242us/step - loss: 0.4213 - acc: 0.7957
Epoch 4/100
7200/7200 [==============================] - 2s 217us/step - loss: 0.4177 - acc: 0.8150
Epoch 5/100
7200/7200 [==============================] - 2s 216us/step - loss: 0.4150 - acc: 0.8229
Epoch 6/100
7200/7200 [==============================] - 2s 215us/step - loss: 0.4140 - acc: 0.8269
Epoch 7/100
7200/7200 [==============================] - 2s 266us/step - loss: 0.4111 - acc: 0.8304
Epoch 8/100
7200/7200 [==============================] - 2s 232us/step - loss: 0.4097 - acc: 0.8336
Epoch 9/100
7200/7200 [==============================] - 2s 211us/step - loss: 0.4088 - acc: 0.8347
Epoch 10/100
7200/7200 [==============================] - 2s 247us/step - loss: 0.4077 - acc: 0.8347
Epoch 11/100
7200/7200 [==============================] - 2s 233us/step - loss: 0.4071 - acc: 0.8371
Epoch 12/100
7200/7200 [==============================] - 2s 247us/step - loss: 0.4057 - acc: 0.8353
Epoch 13/

7200/7200 [==============================] - 2s 283us/step - loss: 0.3951 - acc: 0.8381
Epoch 65/100
7200/7200 [==============================] - 2s 270us/step - loss: 0.3953 - acc: 0.8339
Epoch 66/100
7200/7200 [==============================] - 2s 250us/step - loss: 0.3949 - acc: 0.8361
Epoch 67/100
7200/7200 [==============================] - 2s 263us/step - loss: 0.3950 - acc: 0.8357
Epoch 68/100
7200/7200 [==============================] - 2s 227us/step - loss: 0.3942 - acc: 0.8365
Epoch 69/100
7200/7200 [==============================] - 2s 264us/step - loss: 0.3949 - acc: 0.8362
Epoch 70/100
7200/7200 [==============================] - 2s 275us/step - loss: 0.3941 - acc: 0.8386
Epoch 71/100
7200/7200 [==============================] - 2s 238us/step - loss: 0.3939 - acc: 0.8361
Epoch 72/100
7200/7200 [==============================] - 2s 255us/step - loss: 0.3935 - acc: 0.8386
Epoch 73/100
7200/7200 [==============================] - 2s 261us/step - loss: 0.3929 - acc: 0.8371
Epo

In [0]:
mean = accuracies.mean()
variance = accuracies.std()
variance

0.01690044330007673

In [0]:
mean

0.8349999963492156

low variance

### Dropout regulazation to reduce overfitting

#### Tuning the ANN

In [0]:
from keras.layers import Dropout
from sklearn.model_selection import GridSearchCV

when you have overfitting, you should apply dropout to all the layers

In [0]:
def build_classifier_withDropout(optimizer, init):
    classifier = Sequential()
    classifier.add(Dense(output_dim=6, init=init, activation='relu', input_dim=11))
    #classifier.add(Dropout(p=0.1))
    #Dropout(p, )
    #p: 0-1, fraction of the neurons to drop (disabled).
    #   recommendation: start from 0.1, until overfitting solved. Not exceed 0.5, easy to cause underfitting
    
    classifier.add(Dense(output_dim=6, init=init, activation='relu'))
    #classifier.add(Dropout(p=0.1))
    
    classifier.add(Dense(output_dim=1, init=init, activation='sigmoid'))
    classifier.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])
    return classifier
tuned_classifier = KerasClassifier(build_fn=build_classifier_withDropout)

parameters = {'batch_size': [5, 25, 32],
             'epochs': [100, 500],
             'optimizer': ['adam', 'rmsprop'],
             'init': ['uniform', 'glorot_uniform']}
#comes from experience

grid_search = GridSearchCV(estimator=tuned_classifier, 
                          param_grid = parameters,
                          scoring = 'accuracy',
                          cv = 10)
grid_search = grid_search.fit(X_train, y_train)
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_
best_accuracy

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  if __name__ == '__main__':
/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:12: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  if sys.path[0] == '':


Epoch 1/100
7200/7200 [==============================] - 12s 2ms/step - loss: 0.4627 - acc: 0.7969
Epoch 2/100
7200/7200 [==============================] - 6s 780us/step - loss: 0.4241 - acc: 0.7971
Epoch 3/100
7200/7200 [==============================] - 6s 800us/step - loss: 0.4184 - acc: 0.8192
Epoch 4/100
7200/7200 [==============================] - 5s 741us/step - loss: 0.4154 - acc: 0.8264
Epoch 5/100
7200/7200 [==============================] - 6s 836us/step - loss: 0.4137 - acc: 0.8315
Epoch 6/100
7200/7200 [==============================] - 6s 842us/step - loss: 0.4124 - acc: 0.8319
Epoch 7/100
7200/7200 [==============================] - 5s 730us/step - loss: 0.4103 - acc: 0.8315
Epoch 8/100
7200/7200 [==============================] - 5s 715us/step - loss: 0.4098 - acc: 0.8304
Epoch 9/100
7200/7200 [==============================] - 6s 815us/step - loss: 0.4091 - acc: 0.8339
Epoch 10/100
7200/7200 [==============================] - 6s 807us/step - loss: 0.4079 - acc: 0.8324


7200/7200 [==============================] - 6s 867us/step - loss: 0.4009 - acc: 0.8364
Epoch 64/100
7200/7200 [==============================] - 6s 835us/step - loss: 0.4002 - acc: 0.8342
Epoch 65/100
7200/7200 [==============================] - 6s 795us/step - loss: 0.4007 - acc: 0.8357
Epoch 66/100
7200/7200 [==============================] - 6s 881us/step - loss: 0.4005 - acc: 0.8335
Epoch 67/100
7200/7200 [==============================] - 7s 904us/step - loss: 0.4004 - acc: 0.8354
Epoch 68/100
7200/7200 [==============================] - 6s 844us/step - loss: 0.4007 - acc: 0.8357
Epoch 69/100
7200/7200 [==============================] - 6s 842us/step - loss: 0.4001 - acc: 0.8347
Epoch 70/100
7200/7200 [==============================] - 6s 874us/step - loss: 0.4005 - acc: 0.8354
Epoch 71/100
7200/7200 [==============================] - 5s 734us/step - loss: 0.4006 - acc: 0.8367
Epoch 72/100
7200/7200 [==============================] - 5s 741us/step - loss: 0.4010 - acc: 0.8351
Epo

7200/7200 [==============================] - 5s 750us/step - loss: 0.4018 - acc: 0.8350
Epoch 45/100
7200/7200 [==============================] - 5s 745us/step - loss: 0.4015 - acc: 0.8347
Epoch 46/100
7200/7200 [==============================] - 5s 738us/step - loss: 0.4010 - acc: 0.8349
Epoch 47/100
7200/7200 [==============================] - 5s 738us/step - loss: 0.4014 - acc: 0.8342
Epoch 48/100
7200/7200 [==============================] - 5s 715us/step - loss: 0.4020 - acc: 0.8367
Epoch 49/100
7200/7200 [==============================] - 5s 717us/step - loss: 0.4007 - acc: 0.8346
Epoch 50/100
7200/7200 [==============================] - 5s 723us/step - loss: 0.4011 - acc: 0.8346
Epoch 51/100
7200/7200 [==============================] - 5s 717us/step - loss: 0.4014 - acc: 0.8372
Epoch 52/100
7200/7200 [==============================] - 5s 712us/step - loss: 0.4020 - acc: 0.8365
Epoch 53/100
7200/7200 [==============================] - 5s 718us/step - loss: 0.4011 - acc: 0.8354
Epo

7200/7200 [==============================] - 5s 762us/step - loss: 0.4192 - acc: 0.8249
Epoch 6/100
7200/7200 [==============================] - 6s 780us/step - loss: 0.4171 - acc: 0.8275
Epoch 7/100
7200/7200 [==============================] - 6s 870us/step - loss: 0.4154 - acc: 0.8282
Epoch 8/100
7200/7200 [==============================] - 8s 1ms/step - loss: 0.4148 - acc: 0.8304
Epoch 9/100
7200/7200 [==============================] - 6s 848us/step - loss: 0.4118 - acc: 0.8311
Epoch 10/100
7200/7200 [==============================] - 6s 782us/step - loss: 0.4096 - acc: 0.8315
Epoch 11/100
7200/7200 [==============================] - 5s 742us/step - loss: 0.4082 - acc: 0.8319
Epoch 12/100
7200/7200 [==============================] - 5s 740us/step - loss: 0.4072 - acc: 0.8319
Epoch 13/100
7200/7200 [==============================] - 5s 738us/step - loss: 0.4060 - acc: 0.8322
Epoch 14/100
7200/7200 [==============================] - 5s 737us/step - loss: 0.4052 - acc: 0.8322
Epoch 15/

7200/7200 [==============================] - 7s 933us/step - loss: 0.4006 - acc: 0.8339
Epoch 68/100
7200/7200 [==============================] - 6s 849us/step - loss: 0.4007 - acc: 0.8344
Epoch 69/100
7200/7200 [==============================] - 7s 966us/step - loss: 0.4002 - acc: 0.8333
Epoch 70/100
7200/7200 [==============================] - 8s 1ms/step - loss: 0.4003 - acc: 0.8342
Epoch 71/100
7200/7200 [==============================] - 7s 961us/step - loss: 0.4002 - acc: 0.8347
Epoch 72/100
7200/7200 [==============================] - 6s 834us/step - loss: 0.4005 - acc: 0.8354
Epoch 73/100
7200/7200 [==============================] - 6s 836us/step - loss: 0.4003 - acc: 0.8333
Epoch 74/100
7200/7200 [==============================] - 6s 849us/step - loss: 0.4002 - acc: 0.8351
Epoch 75/100
7200/7200 [==============================] - 6s 771us/step - loss: 0.4002 - acc: 0.8339
Epoch 76/100
7200/7200 [==============================] - 6s 864us/step - loss: 0.4006 - acc: 0.8349
Epoch

accuracy: 0.8506
best parameters: batch_size=25, nb_epoch=500

In [0]:
best_accuracy

0.796

In [0]:
best